package bean;
// Generated 03/10/2025 21:30:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscAparelhos generated by hbm2java
 */
@Entity
@Table(name="msc_aparelhos"
    ,catalog="db_mathias_cacers"
)
public class MscAparelhos  implements java.io.Serializable {


     private int idmscAparelhos;
     private String mscCor;
     private String mscMarca;
     private String mscModelo;
     private String mscNumeroDeSerie;
     private Date mscDataEntrada;
     private String mscChipRetirado;
     private String mscTipodeEquipamento;
     private Set mscOrdemServicoAparelhos = new HashSet(0);

    public MscAparelhos() {
    }

	
    public MscAparelhos(int idmscAparelhos, String mscCor, String mscMarca, String mscModelo, String mscNumeroDeSerie, Date mscDataEntrada, String mscChipRetirado, String mscTipodeEquipamento) {
        this.idmscAparelhos = idmscAparelhos;
        this.mscCor = mscCor;
        this.mscMarca = mscMarca;
        this.mscModelo = mscModelo;
        this.mscNumeroDeSerie = mscNumeroDeSerie;
        this.mscDataEntrada = mscDataEntrada;
        this.mscChipRetirado = mscChipRetirado;
        this.mscTipodeEquipamento = mscTipodeEquipamento;
    }
    public MscAparelhos(int idmscAparelhos, String mscCor, String mscMarca, String mscModelo, String mscNumeroDeSerie, Date mscDataEntrada, String mscChipRetirado, String mscTipodeEquipamento, Set mscOrdemServicoAparelhos) {
       this.idmscAparelhos = idmscAparelhos;
       this.mscCor = mscCor;
       this.mscMarca = mscMarca;
       this.mscModelo = mscModelo;
       this.mscNumeroDeSerie = mscNumeroDeSerie;
       this.mscDataEntrada = mscDataEntrada;
       this.mscChipRetirado = mscChipRetirado;
       this.mscTipodeEquipamento = mscTipodeEquipamento;
       this.mscOrdemServicoAparelhos = mscOrdemServicoAparelhos;
    }
   
     @Id 

    
    @Column(name="idmsc_aparelhos", unique=true, nullable=false)
    public int getIdmscAparelhos() {
        return this.idmscAparelhos;
    }
    
    public void setIdmscAparelhos(int idmscAparelhos) {
        this.idmscAparelhos = idmscAparelhos;
    }

    
    @Column(name="msc_cor", nullable=false, length=20)
    public String getMscCor() {
        return this.mscCor;
    }
    
    public void setMscCor(String mscCor) {
        this.mscCor = mscCor;
    }

    
    @Column(name="msc_marca", nullable=false, length=50)
    public String getMscMarca() {
        return this.mscMarca;
    }
    
    public void setMscMarca(String mscMarca) {
        this.mscMarca = mscMarca;
    }

    
    @Column(name="msc_modelo", nullable=false, length=20)
    public String getMscModelo() {
        return this.mscModelo;
    }
    
    public void setMscModelo(String mscModelo) {
        this.mscModelo = mscModelo;
    }

    
    @Column(name="msc_numero_de_serie", nullable=false, length=30)
    public String getMscNumeroDeSerie() {
        return this.mscNumeroDeSerie;
    }
    
    public void setMscNumeroDeSerie(String mscNumeroDeSerie) {
        this.mscNumeroDeSerie = mscNumeroDeSerie;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_entrada", nullable=false, length=10)
    public Date getMscDataEntrada() {
        return this.mscDataEntrada;
    }
    
    public void setMscDataEntrada(Date mscDataEntrada) {
        this.mscDataEntrada = mscDataEntrada;
    }

    
    @Column(name="msc_chipRetirado", nullable=false, length=100)
    public String getMscChipRetirado() {
        return this.mscChipRetirado;
    }
    
    public void setMscChipRetirado(String mscChipRetirado) {
        this.mscChipRetirado = mscChipRetirado;
    }

    
    @Column(name="msc_tipodeEquipamento", nullable=false, length=20)
    public String getMscTipodeEquipamento() {
        return this.mscTipodeEquipamento;
    }
    
    public void setMscTipodeEquipamento(String mscTipodeEquipamento) {
        this.mscTipodeEquipamento = mscTipodeEquipamento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mscAparelhos")
    public Set getMscOrdemServicoAparelhos() {
        return this.mscOrdemServicoAparelhos;
    }
    
    public void setMscOrdemServicoAparelhos(Set mscOrdemServicoAparelhos) {
        this.mscOrdemServicoAparelhos = mscOrdemServicoAparelhos;
    }




}


