package bean;
// Generated 14/10/2025 12:54:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscClientes generated by hbm2java
 */
@Entity
@Table(name="msc_clientes"
    ,catalog="db_mathias_caceres"
)
public class MscClientes  implements java.io.Serializable {


     private int idmscClientes;
     private String mscNome;
     private String mscCpf;
     private String mscRg;
     private Date mscDataNascimento;
     private String mscTelefone;
     private String mscTelefoneSecundario;
     private String mscEmail;
     private String mscEndereco;
     private String mscBairro;
     private String mscCidade;
     private String mscEstado;
     private String mscCep;
     private Date mscDataCadastro;
     private String mscDeficiencia;
    

    public MscClientes() {
    }

	
    public MscClientes(int idmscClientes, String mscNome, String mscCpf, String mscRg, Date mscDataNascimento, String mscTelefone, String mscTelefoneSecundario, String mscEmail, String mscEndereco, String mscBairro, String mscCidade, String mscEstado, String mscCep, Date mscDataCadastro, String mscDeficiencia) {
        this.idmscClientes = idmscClientes;
        this.mscNome = mscNome;
        this.mscCpf = mscCpf;
        this.mscRg = mscRg;
        this.mscDataNascimento = mscDataNascimento;
        this.mscTelefone = mscTelefone;
        this.mscTelefoneSecundario = mscTelefoneSecundario;
        this.mscEmail = mscEmail;
        this.mscEndereco = mscEndereco;
        this.mscBairro = mscBairro;
        this.mscCidade = mscCidade;
        this.mscEstado = mscEstado;
        this.mscCep = mscCep;
        this.mscDataCadastro = mscDataCadastro;
        this.mscDeficiencia = mscDeficiencia;
    }
    public MscClientes(int idmscClientes, String mscNome, String mscCpf, String mscRg, Date mscDataNascimento, String mscTelefone, String mscTelefoneSecundario, String mscEmail, String mscEndereco, String mscBairro, String mscCidade, String mscEstado, String mscCep, Date mscDataCadastro, String mscDeficiencia, Set mscOrdensServicos) {
       this.idmscClientes = idmscClientes;
       this.mscNome = mscNome;
       this.mscCpf = mscCpf;
       this.mscRg = mscRg;
       this.mscDataNascimento = mscDataNascimento;
       this.mscTelefone = mscTelefone;
       this.mscTelefoneSecundario = mscTelefoneSecundario;
       this.mscEmail = mscEmail;
       this.mscEndereco = mscEndereco;
       this.mscBairro = mscBairro;
       this.mscCidade = mscCidade;
       this.mscEstado = mscEstado;
       this.mscCep = mscCep;
       this.mscDataCadastro = mscDataCadastro;
       this.mscDeficiencia = mscDeficiencia;
 
    }
   
     @Id 

    
    @Column(name="idmsc_clientes", unique=true, nullable=false)
    public int getIdmscClientes() {
        return this.idmscClientes;
    }
    
    public void setIdmscClientes(int idmscClientes) {
        this.idmscClientes = idmscClientes;
    }

    
    @Column(name="msc_nome", nullable=false, length=50)
    public String getMscNome() {
        return this.mscNome;
    }
    
    public void setMscNome(String mscNome) {
        this.mscNome = mscNome;
    }

    
    @Column(name="msc_cpf", nullable=false, length=14)
    public String getMscCpf() {
        return this.mscCpf;
    }
    
    public void setMscCpf(String mscCpf) {
        this.mscCpf = mscCpf;
    }

    
    @Column(name="msc_rg", nullable=false, length=9)
    public String getMscRg() {
        return this.mscRg;
    }
    
    public void setMscRg(String mscRg) {
        this.mscRg = mscRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_nascimento", nullable=false, length=10)
    public Date getMscDataNascimento() {
        return this.mscDataNascimento;
    }
    
    public void setMscDataNascimento(Date mscDataNascimento) {
        this.mscDataNascimento = mscDataNascimento;
    }

    
    @Column(name="msc_telefone", nullable=false, length=11)
    public String getMscTelefone() {
        return this.mscTelefone;
    }
    
    public void setMscTelefone(String mscTelefone) {
        this.mscTelefone = mscTelefone;
    }

    
    @Column(name="msc_telefone_secundario", nullable=false, length=11)
    public String getMscTelefoneSecundario() {
        return this.mscTelefoneSecundario;
    }
    
    public void setMscTelefoneSecundario(String mscTelefoneSecundario) {
        this.mscTelefoneSecundario = mscTelefoneSecundario;
    }

    
    @Column(name="msc_email", nullable=false, length=100)
    public String getMscEmail() {
        return this.mscEmail;
    }
    
    public void setMscEmail(String mscEmail) {
        this.mscEmail = mscEmail;
    }

    
    @Column(name="msc_endereco", nullable=false, length=100)
    public String getMscEndereco() {
        return this.mscEndereco;
    }
    
    public void setMscEndereco(String mscEndereco) {
        this.mscEndereco = mscEndereco;
    }

    
    @Column(name="msc_bairro", nullable=false, length=60)
    public String getMscBairro() {
        return this.mscBairro;
    }
    
    public void setMscBairro(String mscBairro) {
        this.mscBairro = mscBairro;
    }

    
    @Column(name="msc_cidade", nullable=false, length=60)
    public String getMscCidade() {
        return this.mscCidade;
    }
    
    public void setMscCidade(String mscCidade) {
        this.mscCidade = mscCidade;
    }

    
    @Column(name="msc_estado", nullable=false, length=2)
    public String getMscEstado() {
        return this.mscEstado;
    }
    
    public void setMscEstado(String mscEstado) {
        this.mscEstado = mscEstado;
    }

    
    @Column(name="msc_cep", nullable=false, length=9)
    public String getMscCep() {
        return this.mscCep;
    }
    
    public void setMscCep(String mscCep) {
        this.mscCep = mscCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_cadastro", nullable=false, length=10)
    public Date getMscDataCadastro() {
        return this.mscDataCadastro;
    }
    
    public void setMscDataCadastro(Date mscDataCadastro) {
        this.mscDataCadastro = mscDataCadastro;
    }

    
    @Column(name="msc_deficiencia", nullable=false, length=40)
    public String getMscDeficiencia() {
        return this.mscDeficiencia;
    }
    
    public void setMscDeficiencia(String mscDeficiencia) {
        this.mscDeficiencia = mscDeficiencia;
    }




}


