package bean;
// Generated 03/10/2025 21:30:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscOrdensservico generated by hbm2java
 */
@Entity
@Table(name="msc_ordensservico"
    ,catalog="vendas"
)
public class MscOrdensservico  implements java.io.Serializable {


     private Integer idmscOrdensServico;
     private MscClientes mscClientes;
     private MscServicos mscServicos;
     private MscUsuarios mscUsuarios;
     private Date mscDataInicio;
     private String mscStatus;
     private String mscTecnicoResponsavel;
     private BigDecimal mscValorTotal;
     private Set mscOrdemServicoAparelhos = new HashSet(0);

    public MscOrdensservico() {
    }

	
    public MscOrdensservico(Date mscDataInicio, String mscStatus, String mscTecnicoResponsavel, BigDecimal mscValorTotal) {
        this.mscDataInicio = mscDataInicio;
        this.mscStatus = mscStatus;
        this.mscTecnicoResponsavel = mscTecnicoResponsavel;
        this.mscValorTotal = mscValorTotal;
    }
    public MscOrdensservico(MscClientes mscClientes, MscServicos mscServicos, MscUsuarios mscUsuarios, Date mscDataInicio, String mscStatus, String mscTecnicoResponsavel, BigDecimal mscValorTotal, Set mscOrdemServicoAparelhos) {
       this.mscClientes = mscClientes;
       this.mscServicos = mscServicos;
       this.mscUsuarios = mscUsuarios;
       this.mscDataInicio = mscDataInicio;
       this.mscStatus = mscStatus;
       this.mscTecnicoResponsavel = mscTecnicoResponsavel;
       this.mscValorTotal = mscValorTotal;
       this.mscOrdemServicoAparelhos = mscOrdemServicoAparelhos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmsc_ordensServico", unique=true, nullable=false)
    public Integer getIdmscOrdensServico() {
        return this.idmscOrdensServico;
    }
    
    public void setIdmscOrdensServico(Integer idmscOrdensServico) {
        this.idmscOrdensServico = idmscOrdensServico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkmsc_Cliente")
    public MscClientes getMscClientes() {
        return this.mscClientes;
    }
    
    public void setMscClientes(MscClientes mscClientes) {
        this.mscClientes = mscClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkmsc_servico")
    public MscServicos getMscServicos() {
        return this.mscServicos;
    }
    
    public void setMscServicos(MscServicos mscServicos) {
        this.mscServicos = mscServicos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkmsc_usuarios")
    public MscUsuarios getMscUsuarios() {
        return this.mscUsuarios;
    }
    
    public void setMscUsuarios(MscUsuarios mscUsuarios) {
        this.mscUsuarios = mscUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_inicio", nullable=false, length=10)
    public Date getMscDataInicio() {
        return this.mscDataInicio;
    }
    
    public void setMscDataInicio(Date mscDataInicio) {
        this.mscDataInicio = mscDataInicio;
    }

    
    @Column(name="msc_status", nullable=false, length=20)
    public String getMscStatus() {
        return this.mscStatus;
    }
    
    public void setMscStatus(String mscStatus) {
        this.mscStatus = mscStatus;
    }

    
    @Column(name="msc_tecnico_responsavel", nullable=false, length=45)
    public String getMscTecnicoResponsavel() {
        return this.mscTecnicoResponsavel;
    }
    
    public void setMscTecnicoResponsavel(String mscTecnicoResponsavel) {
        this.mscTecnicoResponsavel = mscTecnicoResponsavel;
    }

    
    @Column(name="msc_valorTotal", nullable=false, precision=10)
    public BigDecimal getMscValorTotal() {
        return this.mscValorTotal;
    }
    
    public void setMscValorTotal(BigDecimal mscValorTotal) {
        this.mscValorTotal = mscValorTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mscOrdensservico")
    public Set getMscOrdemServicoAparelhos() {
        return this.mscOrdemServicoAparelhos;
    }
    
    public void setMscOrdemServicoAparelhos(Set mscOrdemServicoAparelhos) {
        this.mscOrdemServicoAparelhos = mscOrdemServicoAparelhos;
    }




}


