package bean;
// Generated 14/10/2025 12:54:27 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscOrdensServico generated by hbm2java
 */
@Entity
@Table(name="msc_ordensServico"
    ,catalog="db_mathias_caceres"
)
public class MscOrdensServico  implements java.io.Serializable {


     private int idmscOrdensServico;
     private MscClientes mscClientes;
     private MscUsuarios mscUsuarios;
     private Date mscDataInicio;
     private String mscStatus;
     private String mscTecnicoResponsavel;
     private BigDecimal mscValorTotal;
   

    public MscOrdensServico() {
    }

	
    public MscOrdensServico(int idmscOrdensServico, Date mscDataInicio, String mscStatus, String mscTecnicoResponsavel, BigDecimal mscValorTotal) {
        this.idmscOrdensServico = idmscOrdensServico;
        this.mscDataInicio = mscDataInicio;
        this.mscStatus = mscStatus;
        this.mscTecnicoResponsavel = mscTecnicoResponsavel;
        this.mscValorTotal = mscValorTotal;
    }
    public MscOrdensServico(int idmscOrdensServico, MscClientes mscClientes, MscUsuarios mscUsuarios, Date mscDataInicio, String mscStatus, String mscTecnicoResponsavel, BigDecimal mscValorTotal, Set mscOrdemServicoAparelhos) {
       this.idmscOrdensServico = idmscOrdensServico;
       this.mscClientes = mscClientes;
       this.mscUsuarios = mscUsuarios;
       this.mscDataInicio = mscDataInicio;
       this.mscStatus = mscStatus;
       this.mscTecnicoResponsavel = mscTecnicoResponsavel;
       this.mscValorTotal = mscValorTotal;
      
    }
   
     @Id 

    
    @Column(name="idmsc_ordensServico", unique=true, nullable=false)
    public int getIdmscOrdensServico() {
        return this.idmscOrdensServico;
    }
    
    public void setIdmscOrdensServico(int idmscOrdensServico) {
        this.idmscOrdensServico = idmscOrdensServico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkmsc_Cliente")
    public MscClientes getMscClientes() {
        return this.mscClientes;
    }
    
    public void setMscClientes(MscClientes mscClientes) {
        this.mscClientes = mscClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkmsc_usuarios")
    public MscUsuarios getMscUsuarios() {
        return this.mscUsuarios;
    }
    
    public void setMscUsuarios(MscUsuarios mscUsuarios) {
        this.mscUsuarios = mscUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_inicio", nullable=false, length=10)
    public Date getMscDataInicio() {
        return this.mscDataInicio;
    }
    
    public void setMscDataInicio(Date mscDataInicio) {
        this.mscDataInicio = mscDataInicio;
    }

    
    @Column(name="msc_status", nullable=false, length=20)
    public String getMscStatus() {
        return this.mscStatus;
    }
    
    public void setMscStatus(String mscStatus) {
        this.mscStatus = mscStatus;
    }

    
    @Column(name="msc_tecnico_responsavel", nullable=false, length=45)
    public String getMscTecnicoResponsavel() {
        return this.mscTecnicoResponsavel;
    }
    
    public void setMscTecnicoResponsavel(String mscTecnicoResponsavel) {
        this.mscTecnicoResponsavel = mscTecnicoResponsavel;
    }

    
    @Column(name="msc_valorTotal", nullable=false, precision=10)
    public BigDecimal getMscValorTotal() {
        return this.mscValorTotal;
    }
    
    public void setMscValorTotal(BigDecimal mscValorTotal) {
        this.mscValorTotal = mscValorTotal;
    }






}


