package bean;
// Generated 03/10/2025 21:30:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MscOrdemServicoAparelho generated by hbm2java
 */
@Entity
@Table(name="msc_ordem_servico_aparelho"
    ,catalog="db_mathias_cacers"
)
public class MscOrdemServicoAparelho  implements java.io.Serializable {


     private int mscIdOsAparelho;
     private MscAparelhos mscAparelhos;
     private MscOrdensservico mscOrdensservico;
     private int mscQuantidade;
     private BigDecimal mscValorUnitario;
     private String mscObservacoes;

    public MscOrdemServicoAparelho() {
    }

	
    public MscOrdemServicoAparelho(int mscIdOsAparelho, int mscQuantidade, BigDecimal mscValorUnitario, String mscObservacoes) {
        this.mscIdOsAparelho = mscIdOsAparelho;
        this.mscQuantidade = mscQuantidade;
        this.mscValorUnitario = mscValorUnitario;
        this.mscObservacoes = mscObservacoes;
    }
    public MscOrdemServicoAparelho(int mscIdOsAparelho, MscAparelhos mscAparelhos, MscOrdensservico mscOrdensservico, int mscQuantidade, BigDecimal mscValorUnitario, String mscObservacoes) {
       this.mscIdOsAparelho = mscIdOsAparelho;
       this.mscAparelhos = mscAparelhos;
       this.mscOrdensservico = mscOrdensservico;
       this.mscQuantidade = mscQuantidade;
       this.mscValorUnitario = mscValorUnitario;
       this.mscObservacoes = mscObservacoes;
    }
   
     @Id 

    
    @Column(name="msc_idOs_Aparelho", unique=true, nullable=false)
    public int getMscIdOsAparelho() {
        return this.mscIdOsAparelho;
    }
    
    public void setMscIdOsAparelho(int mscIdOsAparelho) {
        this.mscIdOsAparelho = mscIdOsAparelho;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="msc_fkAparelho")
    public MscAparelhos getMscAparelhos() {
        return this.mscAparelhos;
    }
    
    public void setMscAparelhos(MscAparelhos mscAparelhos) {
        this.mscAparelhos = mscAparelhos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="msc_fkOs")
    public MscOrdensservico getMscOrdensservico() {
        return this.mscOrdensservico;
    }
    
    public void setMscOrdensservico(MscOrdensservico mscOrdensservico) {
        this.mscOrdensservico = mscOrdensservico;
    }

    
    @Column(name="msc_quantidade", nullable=false)
    public int getMscQuantidade() {
        return this.mscQuantidade;
    }
    
    public void setMscQuantidade(int mscQuantidade) {
        this.mscQuantidade = mscQuantidade;
    }

    
    @Column(name="msc_valor_unitario", nullable=false, precision=10)
    public BigDecimal getMscValorUnitario() {
        return this.mscValorUnitario;
    }
    
    public void setMscValorUnitario(BigDecimal mscValorUnitario) {
        this.mscValorUnitario = mscValorUnitario;
    }

    
    @Column(name="msc_observacoes", nullable=false)
    public String getMscObservacoes() {
        return this.mscObservacoes;
    }
    
    public void setMscObservacoes(String mscObservacoes) {
        this.mscObservacoes = mscObservacoes;
    }




}


