package bean;
// Generated 14/10/2025 12:54:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscServicos generated by hbm2java
 */
@Entity
@Table(name="msc_servicos"
    ,catalog="db_mathias_caceres"
)
public class MscServicos  implements java.io.Serializable {


     private int idmscServicos;
     private String mscNomeServico;
     private String mscDescricao;
     private double mscValor;
     private String mscTempoEstimado;
     private String mscCategoria;
     private Date mscDataCadastro;
   

    public MscServicos() {
    }

	
    public MscServicos(int idmscServicos) {
        this.idmscServicos = idmscServicos;
       
    }
    public MscServicos(int idmscServicos, String mscNomeServico, String mscDescricao, double mscValor, String mscTempoEstimado, String mscCategoria, Date mscDataCadastro, Set mscOrdemServicoAparelhos) {
       this.idmscServicos = idmscServicos;
       this.mscNomeServico = mscNomeServico;
       this.mscDescricao = mscDescricao;
       this.mscValor = mscValor;
       this.mscTempoEstimado = mscTempoEstimado;
       this.mscCategoria = mscCategoria;
       this.mscDataCadastro = mscDataCadastro;
       
    }
   
     @Id 

    
    @Column(name="idmsc_servicos", unique=true, nullable=false)
    public int getIdmscServicos() {
        return this.idmscServicos;
    }
    
    public void setIdmscServicos(int idmscServicos) {
        this.idmscServicos = idmscServicos;
    }

    
    @Column(name="msc_nome_servico", nullable=false, length=150)
    public String getMscNomeServico() {
        return this.mscNomeServico;
    }
    
    public void setMscNomeServico(String mscNomeServico) {
        this.mscNomeServico = mscNomeServico;
    }

    
    @Column(name="msc_descricao", nullable=false)
    public String getMscDescricao() {
        return this.mscDescricao;
    }
    
    public void setMscDescricao(String mscDescricao) {
        this.mscDescricao = mscDescricao;
    }

    
    @Column(name="msc_valor", nullable=false, precision=10)
    public double getMscValor() {
        return this.mscValor;
    }
    
    public void setMscValor(double mscValor) {
        this.mscValor = mscValor;
    }

    
    @Column(name="msc_tempo_estimado", nullable=false, length=100)
    public String getMscTempoEstimado() {
        return this.mscTempoEstimado;
    }
    
    public void setMscTempoEstimado(String mscTempoEstimado) {
        this.mscTempoEstimado = mscTempoEstimado;
    }

    
    @Column(name="msc_categoria", nullable=false, length=50)
    public String getMscCategoria() {
        return this.mscCategoria;
    }
    
    public void setMscCategoria(String mscCategoria) {
        this.mscCategoria = mscCategoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_cadastro", nullable=false, length=10)
    public Date getMscDataCadastro() {
        return this.mscDataCadastro;
    }
    
    public void setMscDataCadastro(Date mscDataCadastro) {
        this.mscDataCadastro = mscDataCadastro;
    }

@Override
    public String toString() {
        return this.idmscServicos + " - " + this.mscNomeServico;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof MscServicos) {
            MscServicos servicos = (MscServicos) object;
            if (servicos.getIdmscServicos() == this.getIdmscServicos()) {
                return true;
            }
        }
        return false;
    }



}


