package bean;
// Generated 03/10/2025 21:30:33 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscServicos generated by hbm2java
 */
@Entity
@Table(name="msc_servicos"
    ,catalog="db_mathias_cacers"
)
public class MscServicos  implements java.io.Serializable {


     private Integer idmscServicos;
     private String mscNomeServico;
     private String mscDescricao;
     private BigDecimal mscValor;
     private String mscTempoEstimado;
     private String mscCategoria;
     private Date mscDataCadastro;
     private Set mscOrdensservicos = new HashSet(0);

    public MscServicos() {
    }

	
    public MscServicos(String mscNomeServico, String mscDescricao, BigDecimal mscValor, String mscTempoEstimado, String mscCategoria, Date mscDataCadastro) {
        this.mscNomeServico = mscNomeServico;
        this.mscDescricao = mscDescricao;
        this.mscValor = mscValor;
        this.mscTempoEstimado = mscTempoEstimado;
        this.mscCategoria = mscCategoria;
        this.mscDataCadastro = mscDataCadastro;
    }
    public MscServicos(String mscNomeServico, String mscDescricao, BigDecimal mscValor, String mscTempoEstimado, String mscCategoria, Date mscDataCadastro, Set mscOrdensservicos) {
       this.mscNomeServico = mscNomeServico;
       this.mscDescricao = mscDescricao;
       this.mscValor = mscValor;
       this.mscTempoEstimado = mscTempoEstimado;
       this.mscCategoria = mscCategoria;
       this.mscDataCadastro = mscDataCadastro;
       this.mscOrdensservicos = mscOrdensservicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmsc_servicos", unique=true, nullable=false)
    public Integer getIdmscServicos() {
        return this.idmscServicos;
    }
    
    public void setIdmscServicos(Integer idmscServicos) {
        this.idmscServicos = idmscServicos;
    }

    
    @Column(name="msc_nome_servico", nullable=false, length=150)
    public String getMscNomeServico() {
        return this.mscNomeServico;
    }
    
    public void setMscNomeServico(String mscNomeServico) {
        this.mscNomeServico = mscNomeServico;
    }

    
    @Column(name="msc_descricao", nullable=false)
    public String getMscDescricao() {
        return this.mscDescricao;
    }
    
    public void setMscDescricao(String mscDescricao) {
        this.mscDescricao = mscDescricao;
    }

    
    @Column(name="msc_valor", nullable=false, precision=10)
    public BigDecimal getMscValor() {
        return this.mscValor;
    }
    
    public void setMscValor(BigDecimal mscValor) {
        this.mscValor = mscValor;
    }

    
    @Column(name="msc_tempo_estimado", nullable=false, length=20)
    public String getMscTempoEstimado() {
        return this.mscTempoEstimado;
    }
    
    public void setMscTempoEstimado(String mscTempoEstimado) {
        this.mscTempoEstimado = mscTempoEstimado;
    }

    
    @Column(name="msc_categoria", nullable=false, length=50)
    public String getMscCategoria() {
        return this.mscCategoria;
    }
    
    public void setMscCategoria(String mscCategoria) {
        this.mscCategoria = mscCategoria;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_data_cadastro", nullable=false, length=10)
    public Date getMscDataCadastro() {
        return this.mscDataCadastro;
    }
    
    public void setMscDataCadastro(Date mscDataCadastro) {
        this.mscDataCadastro = mscDataCadastro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mscServicos")
    public Set getMscOrdensservicos() {
        return this.mscOrdensservicos;
    }
    
    public void setMscOrdensservicos(Set mscOrdensservicos) {
        this.mscOrdensservicos = mscOrdensservicos;
    }




}


