package bean;
// Generated 03/10/2025 21:30:33 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MscUsuarios generated by hbm2java
 */
@Entity
@Table(name="msc_usuarios"
    ,catalog="db_mathias_cacers"
)
public class MscUsuarios  implements java.io.Serializable {


     private Integer idmscUsuarios;
     private String mscNome;
     private String mscApelido;
     private String mscCpf;
     private Date mscDataNascimento;
     private String mscSenha;
     private String mscAtivo;
     private String mscNivel;
     private Set mscOrdensservicos = new HashSet(0);

    public MscUsuarios() {
    }

	
    public MscUsuarios(String mscNome, String mscApelido, String mscCpf, Date mscDataNascimento, String mscSenha, String mscAtivo, String mscNivel) {
        this.mscNome = mscNome;
        this.mscApelido = mscApelido;
        this.mscCpf = mscCpf;
        this.mscDataNascimento = mscDataNascimento;
        this.mscSenha = mscSenha;
        this.mscAtivo = mscAtivo;
        this.mscNivel = mscNivel;
    }
    public MscUsuarios(String mscNome, String mscApelido, String mscCpf, Date mscDataNascimento, String mscSenha, String mscAtivo, String mscNivel, Set mscOrdensservicos) {
       this.mscNome = mscNome;
       this.mscApelido = mscApelido;
       this.mscCpf = mscCpf;
       this.mscDataNascimento = mscDataNascimento;
       this.mscSenha = mscSenha;
       this.mscAtivo = mscAtivo;
       this.mscNivel = mscNivel;
       this.mscOrdensservicos = mscOrdensservicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmsc_usuarios", unique=true, nullable=false)
    public Integer getIdmscUsuarios() {
        return this.idmscUsuarios;
    }
    
    public void setIdmscUsuarios(Integer idmscUsuarios) {
        this.idmscUsuarios = idmscUsuarios;
    }

    
    @Column(name="msc_nome", nullable=false, length=50)
    public String getMscNome() {
        return this.mscNome;
    }
    
    public void setMscNome(String mscNome) {
        this.mscNome = mscNome;
    }

    
    @Column(name="msc_apelido", nullable=false, length=25)
    public String getMscApelido() {
        return this.mscApelido;
    }
    
    public void setMscApelido(String mscApelido) {
        this.mscApelido = mscApelido;
    }

    
    @Column(name="msc_cpf", nullable=false, length=14)
    public String getMscCpf() {
        return this.mscCpf;
    }
    
    public void setMscCpf(String mscCpf) {
        this.mscCpf = mscCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="msc_dataNascimento", nullable=false, length=10)
    public Date getMscDataNascimento() {
        return this.mscDataNascimento;
    }
    
    public void setMscDataNascimento(Date mscDataNascimento) {
        this.mscDataNascimento = mscDataNascimento;
    }

    
    @Column(name="msc_senha", nullable=false, length=20)
    public String getMscSenha() {
        return this.mscSenha;
    }
    
    public void setMscSenha(String mscSenha) {
        this.mscSenha = mscSenha;
    }

    
    @Column(name="msc_ativo", nullable=false, length=10)
    public String getMscAtivo() {
        return this.mscAtivo;
    }
    
    public void setMscAtivo(String mscAtivo) {
        this.mscAtivo = mscAtivo;
    }

    
    @Column(name="msc_nivel", nullable=false, length=20)
    public String getMscNivel() {
        return this.mscNivel;
    }
    
    public void setMscNivel(String mscNivel) {
        this.mscNivel = mscNivel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mscUsuarios")
    public Set getMscOrdensservicos() {
        return this.mscOrdensservicos;
    }
    
    public void setMscOrdensservicos(Set mscOrdensservicos) {
        this.mscOrdensservicos = mscOrdensservicos;
    }




}


